import { query,pool } from '@/lib/db';import { hashPassword } from '@/lib/auth';import { requireSuperAdmin,apiError } from '@/lib/session';export const runtime='nodejs';
const s=v=>String(v??'').trim();const n=v=>v===''||v==null?null:Number(v);
export async function GET(request){try{await requireSuperAdmin(request);const r=await query(`SELECT c.*,count(DISTINCT uc.usuario_id)::int usuarios FROM condominios c LEFT JOIN usuario_condominios uc ON uc.condominio_id=c.id AND uc.ativo=true GROUP BY c.id ORDER BY c.nome`);return Response.json({items:r.rows})}catch(e){return apiError(e)}}
export async function POST(request){let client;try{const actor=await requireSuperAdmin(request);const b=await request.json();if(!s(b.nome)||!s(b.cnpj))return Response.json({error:'Nome e CNPJ são obrigatórios.'},{status:400});client=await pool.connect();await client.query('BEGIN');
 const cr=await client.query(`INSERT INTO condominios(cnpj,nome,razao_social,email,telefone,endereco,responsavel,plano,status,limite_usuarios,ativo) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'ativo',$9,true) RETURNING *`,[s(b.cnpj).replace(/\D/g,''),s(b.nome),s(b.razao_social)||null,s(b.email).toLowerCase()||null,s(b.telefone)||null,s(b.endereco)||null,s(b.responsavel)||null,s(b.plano)||'profissional',n(b.limite_usuarios)]);const c=cr.rows[0];
 await client.query(`INSERT INTO configuracoes_sistema(condominio_id,nome_sistema,cor_primaria) VALUES($1,'Soluções Condo','#2563eb') ON CONFLICT(condominio_id) DO NOTHING`,[c.id]);
 if(s(b.admin_email)){const email=s(b.admin_email).toLowerCase();let ur=await client.query(`SELECT id FROM usuarios WHERE lower(email)=lower($1) LIMIT 1`,[email]);let uid;if(ur.rowCount)uid=ur.rows[0].id;else{if(String(b.admin_senha||'').length<6)throw Object.assign(new Error('Informe senha inicial com pelo menos 6 caracteres.'),{status:400});const hash=await hashPassword(String(b.admin_senha));ur=await client.query(`INSERT INTO usuarios(condominio_id,nome,email,senha_hash,perfil,ativo) VALUES($1,$2,$3,$4,'admin',true) RETURNING id`,[c.id,s(b.admin_nome)||'Administrador',email,hash]);uid=ur.rows[0].id}await client.query(`INSERT INTO usuario_condominios(usuario_id,condominio_id,perfil,ativo) VALUES($1,$2,'admin',true) ON CONFLICT(usuario_id,condominio_id) DO UPDATE SET perfil='admin',ativo=true`,[uid,c.id]);}
 await client.query(`INSERT INTO auditoria_atividades(condominio_id,usuario_id,acao,modulo,entidade_id,descricao) VALUES($1,$2,'criar','condominios',$3,'Condomínio criado pelo Super Administrador')`,[c.id,actor.id,c.id]);await client.query('COMMIT');client.release();return Response.json({item:c},{status:201});
 }catch(e){if(client){try{await client.query('ROLLBACK')}catch{}client.release()}return apiError(e)}}
export async function PATCH(request){try{await requireSuperAdmin(request);const b=await request.json();if(!b.id)return Response.json({error:'ID obrigatório.'},{status:400});const status=['ativo','suspenso','inativo'].includes(b.status)?b.status:null;const r=await query(`UPDATE condominios SET nome=COALESCE($1,nome),razao_social=COALESCE($2,razao_social),email=COALESCE($3,email),telefone=COALESCE($4,telefone),endereco=COALESCE($5,endereco),responsavel=COALESCE($6,responsavel),plano=COALESCE($7,plano),limite_usuarios=COALESCE($8,limite_usuarios),status=COALESCE($9,status),ativo=CASE WHEN $9='ativo' THEN true WHEN $9 IN ('suspenso','inativo') THEN false ELSE ativo END,atualizado_em=now() WHERE id=$10 RETURNING *`,[s(b.nome)||null,s(b.razao_social)||null,s(b.email)||null,s(b.telefone)||null,s(b.endereco)||null,s(b.responsavel)||null,s(b.plano)||null,n(b.limite_usuarios),status,b.id]);if(!r.rowCount)return Response.json({error:'Condomínio não encontrado.'},{status:404});return Response.json({item:r.rows[0]})}catch(e){return apiError(e)}}
