'use client';

import { useEffect, useState } from 'react';
import { Plus, RefreshCw } from 'lucide-react';

const tabs = [['colaboradores', 'Colaboradores'], ['equipamentos', 'Equipamentos'], ['jornadas', 'Jornadas'], ['marcacoes', 'Marcacoes'], ['espelho', 'Espelho de Ponto'], ['banco', 'Banco de Horas'], ['sincronizacoes', 'Sincronizacoes']];
const forms = {
  colaboradores: [{ name: 'nome', label: 'Nome', required: true }, { name: 'cpf', label: 'CPF' }, { name: 'matricula', label: 'Matricula', required: true }, { name: 'cargo', label: 'Cargo' }, { name: 'departamento', label: 'Departamento' }, { name: 'data_admissao', label: 'Admissao', type: 'date' }, { name: 'situacao', label: 'Situacao', type: 'select', options: ['ativo', 'afastado', 'ferias', 'desligado'] }, { name: 'jornada_id', label: 'Jornada', type: 'select', optionKey: 'jornadas' }, { name: 'identificador_controlid', label: 'ID no Control iD', help: 'Somente o identificador, sem biometria.' }],
  equipamentos: [{ name: 'nome', label: 'Nome', required: true }, { name: 'fabricante', label: 'Fabricante', default: 'Control iD' }, { name: 'modelo', label: 'Modelo', default: 'iDFace' }, { name: 'ip', label: 'Endereco IP' }, { name: 'porta', label: 'Porta', type: 'number', default: 80 }, { name: 'firmware', label: 'Versao / firmware' }],
  jornadas: [{ name: 'nome', label: 'Nome', required: true }, { name: 'dias_semana', label: 'Dias da semana', help: 'Numeros 0 a 6 separados por virgula.' }, { name: 'entrada', label: 'Entrada', type: 'time', required: true }, { name: 'inicio_intervalo', label: 'Inicio intervalo', type: 'time' }, { name: 'fim_intervalo', label: 'Fim intervalo', type: 'time' }, { name: 'saida', label: 'Saida', type: 'time', required: true }, { name: 'tolerancia_entrada_min', label: 'Tol. entrada (min)', type: 'number', default: 0 }, { name: 'tolerancia_saida_min', label: 'Tol. saida (min)', type: 'number', default: 0 }, { name: 'tolerancia_intervalo_min', label: 'Tol. intervalo (min)', type: 'number', default: 0 }, { name: 'carga_horaria_min', label: 'Carga diaria (min)', type: 'number', default: 480, required: true }],
  marcacoes: [{ name: 'colaborador_id', label: 'Colaborador', type: 'select', optionKey: 'colaboradores', required: true }, { name: 'data_hora', label: 'Data e hora local', type: 'datetime-local', required: true }, { name: 'tipo', label: 'Tipo', type: 'select', options: ['entrada', 'saida', 'inicio_intervalo', 'fim_intervalo', 'nao_classificada'] }, { name: 'observacao', label: 'Justificativa', type: 'textarea', required: true }],
  banco: [{ name: 'colaborador_id', label: 'Colaborador', type: 'select', optionKey: 'colaboradores', required: true }, { name: 'referencia', label: 'Referencia', type: 'date', required: true }, { name: 'minutos', label: 'Minutos (+ credito / - debito)', type: 'number', required: true }, { name: 'tipo', label: 'Tipo', type: 'select', options: ['credito', 'debito', 'ajuste'] }, { name: 'descricao', label: 'Descricao', type: 'textarea', required: true }],
};

const dateInput = value => { const date = value ? new Date(value) : new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; };
const minuteText = value => { const minutes = Number(value || 0); const sign = minutes < 0 ? '-' : ''; const absolute = Math.abs(minutes); return `${sign}${Math.floor(absolute / 60)}h ${absolute % 60}min`; };
const formatDateTime = value => value ? new Intl.DateTimeFormat('pt-BR', { timeZone: 'America/Bahia', dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '-';

function GenericTable({ rows }) {
  if (!rows.length) return <div className="empty">Nenhum registro encontrado.</div>;
  const columns = Object.keys(rows[0]).filter(key => !['id', 'condominio_id', 'criado_por', 'atualizado_por'].includes(key)).slice(0, 9);
  return <div className="tablewrap"><table className="table"><thead><tr>{columns.map(key => <th key={key}>{key.replaceAll('_', ' ')}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row.id || index}>{columns.map(key => <td key={key}>{row[key] == null ? '-' : typeof row[key] === 'object' ? JSON.stringify(row[key]) : String(row[key])}</td>)}</tr>)}</tbody></table></div>;
}

export default function PontoModule({ auth, initialTab = 'colaboradores', canManage = false }) {
  const [tab, setTab] = useState(initialTab);
  const [items, setItems] = useState([]);
  const [jornadas, setJornadas] = useState([]);
  const [colaboradores, setColaboradores] = useState([]);
  const [summary, setSummary] = useState([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [modal, setModal] = useState(null);
  const [filters, setFilters] = useState({ de: dateInput(new Date(new Date().getFullYear(), new Date().getMonth(), 1)), ate: dateInput(new Date()), colaborador_id: '' });
  const load = async resource => { setBusy(true); setError(''); try { const params = new URLSearchParams(); if (resource === 'espelho' || resource === 'marcacoes') { params.set('de', filters.de); params.set('ate', filters.ate); } if ((resource === 'espelho' || resource === 'banco') && filters.colaborador_id) params.set('colaborador_id', filters.colaborador_id); const query = params.toString() ? `?${params}` : ''; const data = await auth(`/api/ponto/${resource}${query}`); setItems(data.items || []); setSummary(resource === 'espelho' || resource === 'banco' ? data.resumo || [] : []); const [j, c] = await Promise.all([auth('/api/ponto/jornadas'), auth('/api/ponto/colaboradores')]); setJornadas(j.items || []); setColaboradores(c.items || []); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  useEffect(() => { load(tab); }, [tab]);
  const submit = async event => { event.preventDefault(); const payload = Object.fromEntries(new FormData(event.currentTarget).entries()); if (payload.dias_semana) payload.dias_semana = payload.dias_semana.split(',').map(Number).filter(Number.isInteger); try { setBusy(true); await auth(`/api/ponto/${modal}`, { method: 'POST', body: JSON.stringify(payload) }); setModal(null); setNotice('Registro salvo com sucesso.'); await load(tab); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const title = tabs.find(([key]) => key === tab)?.[1] || 'Controle de Ponto';
  const filterBar = (tab === 'espelho' || tab === 'banco' || tab === 'marcacoes') && <div className="ponto-filters"><label>De<input type="date" value={filters.de} onChange={event => setFilters(current => ({ ...current, de: event.target.value }))} /></label><label>Ate<input type="date" value={filters.ate} onChange={event => setFilters(current => ({ ...current, ate: event.target.value }))} /></label>{(tab === 'espelho' || tab === 'banco') && <label>Colaborador<select value={filters.colaborador_id} onChange={event => setFilters(current => ({ ...current, colaborador_id: event.target.value }))}><option value="">Todos</option>{colaboradores.map(item => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></label>}<button className="btn light small" onClick={() => load(tab)} disabled={busy}>Aplicar</button></div>;
  return <section className="ponto-shell"><div className="ponto-tabs">{tabs.map(([key, label]) => <button key={key} className={`tab ${tab === key ? 'active' : ''}`} onClick={() => setTab(key)}>{label}</button>)}</div>{(notice || error) && <div className={error ? 'errorbox' : 'successbox'}>{error || notice}</div>}<div className="ponto-toolbar"><div><h2>{title}</h2><p className="muted">Horarios exibidos no fuso America/Bahia.</p></div><div className="actions"><button className="btn light small" onClick={() => load(tab)} disabled={busy}><RefreshCw size={14}/>Atualizar</button>{canManage && forms[tab] && <button className="btn primary small" onClick={() => setModal(tab)}><Plus size={14}/>Novo</button>}</div></div>{filterBar}{modal && canManage && <form className="ponto-form" onSubmit={submit}><div className="form-grid">{forms[modal].map(field => <div className={`field ${field.type === 'textarea' ? 'full' : ''}`} key={field.name}><label>{field.label}{field.required ? ' *' : ''}</label>{field.type === 'textarea' ? <textarea name={field.name} required={field.required}/> : field.type === 'select' ? <select name={field.name} defaultValue={field.default || ''} required={field.required}><option value="">Selecione</option>{(field.optionKey === 'jornadas' ? jornadas : field.optionKey === 'colaboradores' ? colaboradores : field.options || []).map(item => <option key={item.id || item} value={item.id || item}>{item.nome || item}</option>)}</select> : <input name={field.name} type={field.type || 'text'} defaultValue={field.default || ''} required={field.required}/>} {field.help && <span className="helper">{field.help}</span>}</div>)}</div><div className="modalfoot"><button type="button" className="btn light" onClick={() => setModal(null)}>Cancelar</button><button className="btn primary" disabled={busy}>Salvar</button></div></form>}{tab === 'espelho' ? <><div className="ponto-summary-grid">{summary.map(row => <div className="ponto-summary" key={`${row.colaborador_id}-${row.data}`}><strong>{row.colaborador} - {row.data}</strong><span>Previsto: {minuteText(row.previsto_min)}</span><span>Trabalhado: {minuteText(row.trabalhado_min)}</span><span>Atraso: {minuteText(row.atraso_min)} - Extra: {minuteText(row.extra_min)}</span><b>Saldo: {minuteText(row.saldo_min)}{row.incompleto ? ' - Incompleto' : ''}</b><small>{row.marcacoes.map(mark => `${mark.tipo}: ${formatDateTime(mark.data_hora)}`).join(' | ') || 'Sem marcacoes'}</small></div>)}</div>{!summary.length && <div className="empty">Nenhum espelho encontrado.</div>}</> : tab === 'banco' ? <><div className="ponto-summary-grid">{summary.map(row => <div className="ponto-summary" key={row.colaborador_id}><strong>{row.colaborador}</strong><span>Creditos: {minuteText(row.creditos_min)}</span><span>Debitos: {minuteText(row.debitos_min)}</span><b>Saldo: {minuteText(row.saldo_min)}</b></div>)}</div><GenericTable rows={items}/></> : <GenericTable rows={items}/>}</section>;
}
