import { query,pool } from '@/lib/db';
import { hashPassword } from '@/lib/auth';
import { requireSuperAdmin,apiError } from '@/lib/session';
export const runtime='nodejs';
const s=v=>String(v??'').trim();
const statusOk=v=>['pendente','ativo','suspenso','vencido','bloqueado'].includes(v);
export async function GET(request){try{await requireSuperAdmin(request);const r=await query(`SELECT u.id,u.nome,u.email,u.ativo,u.licenca_status,u.licenca_inicio,u.licenca_fim,u.limite_condominios,count(c.id)::int condominios FROM usuarios u LEFT JOIN condominios c ON c.sindico_id=u.id WHERE u.tipo_conta='sindico' GROUP BY u.id ORDER BY u.nome`);return Response.json({items:r.rows})}catch(e){return apiError(e)}}
export async function POST(request){try{await requireSuperAdmin(request);const b=await request.json();if(!s(b.nome)||!s(b.email))return Response.json({error:'Nome e e-mail são obrigatórios.'},{status:400});if(String(b.senha||'').length<6)return Response.json({error:'A senha inicial deve ter pelo menos 6 caracteres.'},{status:400});const hash=await hashPassword(String(b.senha));const r=await query(`INSERT INTO usuarios(nome,email,senha_hash,perfil,ativo,is_superadmin,tipo_conta,licenca_status,limite_condominios) VALUES($1,$2,$3,'admin',true,false,'sindico','pendente',0) RETURNING id,nome,email,licenca_status,limite_condominios`,[s(b.nome),s(b.email).toLowerCase(),hash]);return Response.json({item:r.rows[0]},{status:201})}catch(e){if(e?.code==='23505')return Response.json({error:'E-mail já cadastrado.'},{status:409});return apiError(e)}}
export async function PATCH(request){let client;try{const actor=await requireSuperAdmin(request);const b=await request.json();if(!b.id)return Response.json({error:'ID do síndico obrigatório.'},{status:400});const limite=Math.max(0,Number(b.limite_condominios??0));if(!Number.isInteger(limite))return Response.json({error:'Quantidade de condomínios inválida.'},{status:400});const status=statusOk(b.licenca_status)?b.licenca_status:'ativo';if(status==='ativo'&&(!b.licenca_inicio||!b.licenca_fim))return Response.json({error:'Informe início e fim da licença.'},{status:400});if(b.licenca_inicio&&b.licenca_fim&&b.licenca_fim<b.licenca_inicio)return Response.json({error:'A data final deve ser posterior à inicial.'},{status:400});client=await pool.connect();await client.query('BEGIN');const used=await client.query(`SELECT count(*)::int total FROM condominios WHERE sindico_id=$1`,[b.id]);if(limite<used.rows[0].total)throw Object.assign(new Error(`O síndico já possui ${used.rows[0].total} condomínio(s). O limite não pode ser menor.`),{status:409});const r=await client.query(`UPDATE usuarios SET licenca_status=$1,licenca_inicio=$2,licenca_fim=$3,limite_condominios=$4,ativo=CASE WHEN $1='bloqueado' THEN false ELSE true END WHERE id=$5 AND tipo_conta='sindico' RETURNING id,nome,email,licenca_status,licenca_inicio,licenca_fim,limite_condominios,ativo`,[status,b.licenca_inicio||null,b.licenca_fim||null,limite,b.id]);if(!r.rowCount)throw Object.assign(new Error('Síndico não encontrado.'),{status:404});await client.query(`INSERT INTO auditoria_atividades(usuario_id,acao,modulo,entidade_id,descricao) VALUES($1,'licenciar','sindicos',$2,$3)`,[actor.id,b.id,`Licença ${status}; limite ${limite}; validade ${b.licenca_inicio||'-'} a ${b.licenca_fim||'-'}`]);await client.query('COMMIT');client.release();return Response.json({item:r.rows[0]})}catch(e){if(client){try{await client.query('ROLLBACK')}catch{}client.release()}return apiError(e)}}
