import {query} from '@/lib/db';
import {apiError} from '@/lib/session';
import {staff,body,fail,text,uuid,amount,transaction,own,event,localDate} from '@/lib/operacao';
import {executeChecklist,updateWorkOrder,saveReservation,saveNotice,alerts} from '@/lib/operacao-services';
import {importRows} from '@/lib/importacao';
import {hashPassword} from '@/lib/auth';
import {issueRecovery} from '@/lib/recovery';
export const runtime='nodejs';
const management=['areas','bloqueios','comunicados','importar','implantacao','acessos','recuperacoes'];
export async function GET(request,{params}){try{
 const {action}=await params;const u=await staff(request,management.includes(action)&&!['comunicados','bloqueios'].includes(action)),cid=u.condominio_id;const q=new URL(request.url).searchParams;let result;
 switch(action){
 case 'checklists': result=(await query(`SELECT e.*,m.nome,u.nome executor,(SELECT json_agg(json_build_object('item',i.descricao,'resposta',r.resposta,'observacao',r.observacao,'foto',r.foto_data_url)) FROM checklist_respostas r JOIN checklist_modelo_itens i ON i.id=r.item_id WHERE r.execucao_id=e.id AND r.condominio_id=$1) respostas FROM checklist_execucoes e JOIN checklist_modelos m ON m.id=e.modelo_id JOIN usuarios u ON u.id=e.executado_por WHERE e.condominio_id=$1 ORDER BY e.executado_em DESC LIMIT 100`,[cid])).rows;break;
 case 'os': {const o=await own({query},'ordens_servico',q.get('id'),cid);const history=(await query(`SELECT e.*,u.nome autor FROM operacao_eventos e LEFT JOIN usuarios u ON u.id=e.usuario_id WHERE e.condominio_id=$1 AND e.entidade='os' AND e.entidade_id=$2 ORDER BY e.criado_em`,[cid,o.id])).rows;return Response.json({item:o,history});}
 case 'alertas':result=await alerts(u);break;
 case 'bloqueios':result=(await query('SELECT * FROM reservas_bloqueios WHERE condominio_id=$1 AND ativo ORDER BY inicio',[cid])).rows;break;
 case 'comunicados':result=(await query(`SELECT c.*,(SELECT count(*)::int FROM comunicados_leituras l WHERE l.comunicado_id=c.id AND l.versao=c.versao) leituras FROM comunicados c WHERE c.condominio_id=$1 AND ($2 OR (c.publicado AND (c.agendado_em IS NULL OR c.agendado_em<=now()) AND c.publico IN ('todos','equipe'))) ORDER BY c.criado_em DESC LIMIT 200`,[cid,u.is_superadmin||['admin','gerente','supervisor'].includes(u.perfil)])).rows;break;
 case 'comunicado_historico':{const notice=await own({query},'comunicados',q.get('id'),cid);if(notice.publico==='administracao'&&!['admin','gerente','supervisor'].includes(u.perfil)&&!u.is_superadmin)fail('Acesso restrito.',403);result=(await query('SELECT versao,dados,criado_em FROM comunicados_versoes WHERE condominio_id=$1 AND comunicado_id=$2 ORDER BY versao DESC',[cid,notice.id])).rows;break;}
 case 'plantao':result=(await query(`SELECT p.*,u.nome autor,r.nome recebedor FROM passagens_plantao p JOIN usuarios u ON u.id=p.usuario_id LEFT JOIN usuarios r ON r.id=p.recebido_por WHERE p.condominio_id=$1 ORDER BY p.criado_em DESC LIMIT 100`,[cid])).rows;break;
 case 'custos':result=(await query(`SELECT i.id,i.descricao,i.patrimonio,i.valor_aquisicao,count(o.id)::int ordens,COALESCE(sum(o.custo_real),0) custo_total FROM inventario i LEFT JOIN ordens_servico o ON o.inventario_id=i.id AND o.condominio_id=i.condominio_id AND o.status='concluida' WHERE i.condominio_id=$1 AND i.ativo GROUP BY i.id ORDER BY custo_total DESC`,[cid])).rows;break;
 case 'acessos':result=(await query(`SELECT m.id,m.nome,m.email,u.bloco,u.unidade,a.id acesso_id,a.ativo FROM moradores m JOIN unidades u ON u.id=m.unidade_id AND u.condominio_id=m.condominio_id LEFT JOIN moradores_acessos a ON a.morador_id=m.id AND a.condominio_id=m.condominio_id WHERE m.condominio_id=$1 AND m.ativo ORDER BY m.nome`,[cid])).rows;break;
 case 'recuperacoes':result=(await query(`SELECT id,email,tipo,criado_em,expira_em,atendido_por FROM recuperacoes_senha WHERE condominio_id=$1 AND usado_em IS NULL AND criado_em>now()-interval '7 days' ORDER BY criado_em DESC LIMIT 100`,[cid])).rows;break;
 case 'implantacao':{const counts=(await query(`SELECT (SELECT count(*) FROM unidades WHERE condominio_id=$1 AND ativo)::int unidades,(SELECT count(*) FROM moradores WHERE condominio_id=$1 AND ativo)::int moradores,(SELECT count(*) FROM inventario WHERE condominio_id=$1 AND ativo)::int inventario,(SELECT count(*) FROM areas_reservaveis WHERE condominio_id=$1 AND ativo)::int areas,(SELECT count(*) FROM checklist_modelos WHERE condominio_id=$1 AND ativo)::int checklists,(SELECT count(*) FROM moradores_acessos WHERE condominio_id=$1 AND ativo)::int acessos`,[cid])).rows[0];return Response.json({counts});}
 default:fail('Recurso não encontrado.',404);
 }
 return Response.json({items:result});
 }catch(e){return apiError(e)}}
export async function POST(request,{params}){try{
 const {action}=await params;const u=await staff(request,management.includes(action)),cid=u.condominio_id,b=await body(request);let item;
 switch(action){
 case 'checklists':item=await executeChecklist(u,b);break;
 case 'os':item=await updateWorkOrder(u,b);break;
 case 'reservas':item=await saveReservation(u,b);break;
 case 'comunicados':item=await saveNotice(u,b);break;
 case 'areas':item=await transaction(async c=>{await own(c,'areas_reservaveis',b.id,cid,true);const regras={antecedencia_horas:amount(b.antecedencia_horas||0),cancelamento_horas:amount(b.cancelamento_horas||0),duracao_max_horas:amount(b.duracao_max_horas||0),limite_mensal:amount(b.limite_mensal||0),abertura:text(b.abertura,5),fechamento:text(b.fechamento,5)};if(!Number.isInteger(regras.limite_mensal))fail('O limite mensal deve ser inteiro.');if((regras.abertura||regras.fechamento)&&(!/^([01]\d|2[0-3]):[0-5]\d$/.test(regras.abertura)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(regras.fechamento)||regras.abertura>=regras.fechamento))fail('Informe abertura e fechamento válidos.');const r=await c.query('UPDATE areas_reservaveis SET regras=$1,regulamento=$2,valor_taxa=$3 WHERE id=$4 AND condominio_id=$5 RETURNING *',[JSON.stringify(regras),text(b.regulamento,15000),amount(b.valor_taxa||0),b.id,cid]);await event(c,u,'areas',b.id,'regras_alteradas');return r.rows[0]});break;
 case 'bloqueios':item=await transaction(async c=>{if(b.id){const r=await c.query('UPDATE reservas_bloqueios SET ativo=false WHERE id=$1 AND condominio_id=$2 RETURNING id',[uuid(b.id),cid]);if(!r.rowCount)fail('Bloqueio não encontrado.',404);return r.rows[0]};await own(c,'areas_reservaveis',b.area_id,cid,true);const start=localDate(b.inicio),end=localDate(b.fim);if(end<=start||!text(b.motivo))fail('Informe motivo e período válido.');const conflicts=await c.query("SELECT id FROM reservas WHERE condominio_id=$1 AND area_id=$2 AND status='confirmada' AND inicio<$4 AND fim>$3",[cid,b.area_id,start,end]);if(conflicts.rowCount)fail('Existem reservas confirmadas neste período. Reagende ou cancele antes de bloquear.',409);return (await c.query('INSERT INTO reservas_bloqueios(condominio_id,area_id,inicio,fim,motivo,criado_por) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[cid,b.area_id,start,end,text(b.motivo),u.id])).rows[0]});break;
 case 'alertas':{if(!text(b.providencia))fail('Registre a providência.');const available=await alerts(u);if(!available.some(a=>a.chave===b.chave))fail('Alerta não encontrado.',404);await query(`INSERT INTO alertas_acompanhamento(condominio_id,chave,usuario_id,providencia) VALUES($1,$2,$3,$4) ON CONFLICT(condominio_id,chave) DO UPDATE SET usuario_id=EXCLUDED.usuario_id,providencia=EXCLUDED.providencia,visto_em=now()`,[cid,b.chave,u.id,text(b.providencia)]);item={ok:true};break;}
 case 'leitura':{const n=await own({query},'comunicados',b.id,cid);if(!n.publicado||(n.agendado_em&&new Date(n.agendado_em)>new Date())||(n.publico==='administracao'&&!u.is_superadmin&&!['admin','gerente','supervisor'].includes(u.perfil)))fail('Comunicado indisponível.',403);await query("INSERT INTO comunicados_leituras(comunicado_id,condominio_id,leitor_id,tipo,versao) VALUES($1,$2,$3,'equipe',$4) ON CONFLICT DO NOTHING",[n.id,cid,u.id,n.versao]);item={ok:true};break;}
 case 'plantao':{if(b.id){const r=await query('UPDATE passagens_plantao SET recebido_por=$1,recebido_em=now() WHERE id=$2 AND condominio_id=$3 AND recebido_em IS NULL AND usuario_id<>$1 RETURNING id',[u.id,uuid(b.id),cid]);if(!r.rowCount)fail('O plantão já foi recebido ou foi registrado por você.',409);item=r.rows[0];}else{if(!text(b.turno)||!text(b.pendencias))fail('Informe turno e pendências.');item=(await query('INSERT INTO passagens_plantao(condominio_id,usuario_id,turno,pendencias) VALUES($1,$2,$3,$4) RETURNING *',[cid,u.id,text(b.turno,100),text(b.pendencias)])).rows[0]}break;}
 case 'importar':item=await importRows(u,b);break;
 case 'acessos':{if(!u.is_superadmin&&u.perfil!=='admin')fail('Somente o administrador pode gerenciar acessos.',403);const m=await own({query},'moradores',b.morador_id,cid);if(!m.email||!/^\S+@\S+\.\S+$/.test(m.email))fail('Cadastre um e-mail válido para este morador.');if(b.ativo!==undefined){await query('UPDATE moradores_acessos SET ativo=$1 WHERE morador_id=$2 AND condominio_id=$3',[!!b.ativo,m.id,cid]);item={ok:true};break;}if(String(b.senha||'').length<10)fail('Use uma senha inicial com pelo menos 10 caracteres.');const hash=await hashPassword(b.senha);item=(await query(`INSERT INTO moradores_acessos(condominio_id,morador_id,email,senha_hash) VALUES($1,$2,$3,$4) ON CONFLICT(condominio_id,morador_id) DO UPDATE SET email=EXCLUDED.email,senha_hash=EXCLUDED.senha_hash,ativo=true,senha_alterada_em=now() RETURNING id,email`,[cid,m.id,m.email.trim().toLowerCase(),hash])).rows[0];break;}
 case 'recuperacoes':if(!u.is_superadmin&&u.perfil!=='admin')fail('Somente o administrador pode atender recuperações.',403);item=await issueRecovery(u,b.id);break;
 default:fail('Operação não encontrada.',404);
 }
 return Response.json({item});
 }catch(e){return apiError(e)}}
