'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {ArrowRight,Building2,CalendarDays,CheckCircle2,ClipboardCheck,FileText,Gauge,HardHat,LayoutDashboard,PackageSearch,ShieldCheck,Smartphone,Sparkles,UsersRound,Wrench,Menu,X,CreditCard,Boxes,Bell,ShoppingCart,KeyRound} from 'lucide-react';

const modules=[
 {icon:LayoutDashboard,title:'Painel operacional',text:'Indicadores, prioridades e visão consolidada da rotina de cada condomínio.'},
 {icon:Building2,title:'Gestão multi-condomínio',text:'Síndicos administram seus condomínios em um único acesso, mantendo os dados isolados.'},
 {icon:CreditCard,title:'Autorização de pagamentos',text:'Solicitações por diretoria, parcelas, vencimentos e dupla validação entre Administração e Diretor.'},
 {icon:Wrench,title:'Manutenção e O.S.',text:'Planos preventivos, ordens de serviço, responsáveis, prioridades e histórico.'},
 {icon:ClipboardCheck,title:'Checklists e ocorrências',text:'Inspeções operacionais, evidências, pendências e acompanhamento da resolução.'},
 {icon:CalendarDays,title:'Reservas e agenda',text:'Eventos, valores, pagamentos, vencimentos, agenda e comunicação com o solicitante.'},
 {icon:Boxes,title:'Patrimônio e suprimentos',text:'Inventário, estoque, materiais, ferramentas e movimentações centralizados.'},
 {icon:ShoppingCart,title:'Compras e fornecedores',text:'Fornecedores, orçamentos, cotações, contratos e documentos em um só fluxo.'},
 {icon:UsersRound,title:'Equipe e acessos',text:'Perfis por função, equipe por condomínio, Diretorias e acesso conforme competência.'},
];
const benefits=['Menos planilhas e informações espalhadas','Visão de vários condomínios no mesmo acesso','Responsabilidades e aprovações rastreáveis','Histórico operacional para prestação de contas','Acesso pelo celular, tablet ou computador','Dados separados e protegidos por condomínio'];
const wa=(msg='Quero conhecer o Soluções Condo')=>`https://wa.me/5571997045391?text=${encodeURIComponent(msg)}`;

export default function CommercialPage(){
 const [menuOpen,setMenuOpen]=useState(false),[logged,setLogged]=useState(false);
 useEffect(()=>setLogged(Boolean(localStorage.getItem('token'))),[]);const accessHref=logged?'/dashboard':'/login';
 return <main className="landing">
  <header className="landing-nav"><div className="landing-container nav-inner">
   <Link href="/" className="landing-brand"><div className="landing-brandmark"><Building2 size={22}/></div><div><strong>Soluções Condo</strong><span>Gestão Operacional</span></div></Link>
   <nav className="desktop-nav"><a href="#solucao">A plataforma</a><a href="#modulos">Recursos</a><a href="#gestao">Para quem é</a><a href="#contato">Fale conosco</a></nav>
   <div className="nav-cta"><Link href={accessHref} className="landing-btn ghost">{logged?'Ir para o painel':'Acessar sistema'}</Link><a href={wa()} target="_blank" rel="noreferrer" className="landing-btn primary">Solicitar apresentação <ArrowRight size={17}/></a></div>
   <button className="mobile-menu-btn" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button>
  </div>{menuOpen&&<div className="mobile-menu"><a href="#modulos">Recursos</a><a href="#gestao">Para quem é</a><a href="#contato">Contato</a><Link href={accessHref} className="landing-btn primary">Acessar sistema</Link></div>}</header>

  <section className="hero" id="solucao"><div className="hero-glow one"/><div className="hero-glow two"/><div className="landing-container hero-grid">
   <div className="hero-copy"><div className="eyebrow"><Sparkles size={16}/> O condomínio inteiro em uma única operação</div><h1>Gestão condominial com controle, responsabilidade e visão em tempo real.</h1><p>O Soluções Condo conecta síndicos, administradores, diretores e equipes em uma plataforma criada para acompanhar o que realmente acontece na operação: pendências, manutenção, checklists, reservas, patrimônio, fornecedores, documentos e autorizações de pagamento.</p><div className="hero-actions"><a href={wa('Olá! Gostaria de agendar uma apresentação do Soluções Condo.')} target="_blank" rel="noreferrer" className="landing-btn primary large">Quero conhecer o sistema <ArrowRight size={19}/></a><Link href={accessHref} className="landing-btn light large">{logged?'Abrir meu painel':'Já sou cliente'}</Link></div><div className="hero-trust"><span><CheckCircle2/> Multi-condomínio</span><span><CheckCircle2/> Perfis e permissões</span><span><CheckCircle2/> 100% web</span></div></div>
   <div className="hero-product"><div className="product-window"><div className="window-bar"><span/><span/><span/><div>Soluções Condo • Visão geral</div></div><div className="product-layout">
    <aside className="mock-sidebar"><div className="mock-logo"><Building2 size={18}/></div>{[[LayoutDashboard,'Visão geral'],[Building2,'Meus condomínios'],[CreditCard,'Autoriz. pagamentos'],[Bell,'Notificações'],[CalendarDays,'Agenda'],[Wrench,'Manutenção'],[ClipboardCheck,'Checklists'],[UsersRound,'Equipe e acessos']].map(([Icon,t],i)=><div key={t} className={`mock-nav ${i===0?'active':''}`}><Icon size={15}/><span>{t}</span></div>)}</aside>
    <div className="mock-main"><div className="mock-top"><div><small>RESUMO OPERACIONAL</small><strong>Visão geral do condomínio</strong></div><div className="mock-avatar">EN</div></div><div className="mock-metrics"><div><Gauge/><span>Pendências abertas</span><strong>12</strong></div><div><Wrench/><span>Manutenções</span><strong>03</strong></div><div><ClipboardCheck/><span>Checklists</span><strong>08</strong></div></div><div className="mock-panels"><div className="mock-card large-card"><div className="mock-card-title"><strong>Prioridades da operação</strong><span>Hoje</span></div>{[['Pagamento','NF 1842 • Diretoria Financeira','Aguardando diretor'],['Manutenção','Bomba da piscina','Em andamento'],['Checklist','Área comum','Pendente']].map((r,i)=><div className="mock-row" key={i}><div className={`mock-dot d${i}`}/><div><strong>{r[0]}</strong><span>{r[1]}</span></div><em>{r[2]}</em></div>)}</div><div className="mock-card"><div className="mock-card-title"><strong>Governança</strong></div><div className="progress-ring">92<small>%</small></div><p>Rotinas acompanhadas</p></div></div></div>
   </div></div><div className="floating-card fc-one"><ShieldCheck/><div><strong>Acesso por competência</strong><span>Cada perfil vê o que precisa</span></div></div><div className="floating-card fc-two"><Smartphone/><div><strong>Operação na mão</strong><span>Celular e computador</span></div></div></div>
  </div></section>

  <section className="proof-strip"><div className="landing-container proof-grid"><div><strong>Multi-condomínio</strong><span>gestão centralizada para o síndico</span></div><div><strong>Dupla validação</strong><span>Administração + Diretoria</span></div><div><strong>Operação rastreável</strong><span>histórico e responsabilidades</span></div><div><strong>Dados isolados</strong><span>segurança por condomínio</span></div></div></section>

  <section className="landing-section modules-section" id="modulos"><div className="landing-container"><div className="section-heading centered"><span className="section-kicker">O SISTEMA ATUAL</span><h2>Da rotina operacional à decisão da gestão</h2><p>Uma plataforma ampla, construída para substituir controles dispersos por processos claros, responsáveis definidos e informação centralizada.</p></div><div className="modules-grid">{modules.map(({icon:Icon,title,text})=><article className="module-card" key={title}><div className="module-icon"><Icon/></div><h3>{title}</h3><p>{text}</p><span>Integrado à plataforma <ArrowRight size={15}/></span></article>)}</div></div></section>

  <section className="landing-section alt" id="gestao"><div className="landing-container split-section"><div className="visual-stack"><div className="visual-card main-visual"><div className="mini-head"><span>Fluxo de autorização</span><CreditCard/></div><div style={{padding:'28px 10px',display:'grid',gap:14}}>{['Solicitação cadastrada','Administração valida','Diretor da competência valida','Liberado para pagamento'].map((x,i)=><div key={x} style={{display:'flex',alignItems:'center',gap:12,fontWeight:700}}><span style={{width:30,height:30,borderRadius:30,display:'grid',placeItems:'center',background:'#edf5ff',color:'#0b5cff'}}>{i+1}</span>{x}</div>)}</div></div><div className="visual-card mini-visual"><KeyRound/><div><strong>Perfis e permissões</strong><span>Síndico, administração, diretor e equipe</span></div></div></div><div className="section-heading"><span className="section-kicker">GESTÃO COM GOVERNANÇA</span><h2>Quem precisa decidir enxerga. Quem precisa executar sabe o que fazer.</h2><p>O sistema organiza o acesso e as responsabilidades de cada pessoa. Diretores acompanham sua competência, equipes trabalham no condomínio autorizado e o síndico mantém a visão dos condomínios sob sua gestão.</p><div className="benefit-list">{benefits.map(x=><div key={x}><CheckCircle2/><span>{x}</span></div>)}</div></div></div></section>

  <section className="landing-section"><div className="landing-container"><div className="section-heading centered"><span className="section-kicker">FEITO PARA A OPERAÇÃO REAL</span><h2>Uma plataforma para quem administra e para quem executa</h2><p>O Soluções Condo aproxima gestão e operação sem transformar a rotina em burocracia.</p></div><div className="audience-grid"><article><div><Building2/></div><h3>Síndicos e administradoras</h3><p>Gerencie múltiplos condomínios, indicadores, licenças, equipes e prioridades em uma visão organizada.</p></article><article><div><HardHat/></div><h3>Administradores e equipes</h3><p>Registre demandas, acompanhe manutenção, checklists, reservas, materiais, fornecedores e documentos.</p></article><article><div><CreditCard/></div><h3>Diretores</h3><p>Acesse somente as pendências da sua competência e participe das autorizações com rastreabilidade.</p></article></div></div></section>

  <section className="landing-section cta-section" id="contato"><div className="landing-container"><div className="cta-box"><div><span className="section-kicker">SOLUÇÕES CONDO</span><h2>Veja como a plataforma pode organizar a operação dos seus condomínios.</h2><p>Solicite uma apresentação e conheça o sistema aplicado ao dia a dia da sua gestão.</p></div><div className="cta-actions"><a href={wa('Olá! Gostaria de conhecer o Soluções Condo e agendar uma apresentação.')} target="_blank" rel="noreferrer" className="landing-btn primary large">Falar pelo WhatsApp <ArrowRight size={18}/></a><Link href="/demonstracao" className="landing-btn light large">Ver demonstração</Link></div></div></div></section>
 </main>
}