'use client';
import {useEffect,useMemo,useState} from 'react';
const brl=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
const dt=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';
const d=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(String(v).slice(0,10)+'T12:00:00-03:00')):'—';
export default function PaymentAuthorizationPanel(){
 const [items,setItems]=useState([]),[dirs,setDirs]=useState([]),[me,setMe]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[formOpen,setFormOpen]=useState(false),[dirOpen,setDirOpen]=useState(false),[directorOpen,setDirectorOpen]=useState(false),[filter,setFilter]=useState(''),[form,setForm]=useState({forma_pagamento:'avista',notificar_diretor:true,lembrete_dias_antes:3,parcelas:[{numero:1,valor:'',vencimento:''}]});
 const token=()=>localStorage.getItem('token'),cid=()=>localStorage.getItem('condominio_id');
 async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...(opt.body?{'Content-Type':'application/json'}:{}),Authorization:`Bearer ${token()}`,...(cid()?{'X-Condominio-Id':cid()}:{}),...(opt.headers||{})},cache:'no-store'});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'Falha na operação.');return x}
 async function load(){setLoading(true);setError('');try{const [a,b,m]=await Promise.all([api('/api/autorizacoes-pagamento'),api('/api/diretorias'),api('/api/me')]);setItems(a.items||[]);setDirs(b.items||[]);setMe(m)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{if(!token()){location.href='/login';return}load()},[]);
 const visible=useMemo(()=>items.filter(x=>!filter||x.diretoria_id===filter),[items,filter]);
 const isDirector=me?.user?.tipo_conta==='diretor',isAdmin=me?.user?.is_superadmin||me?.user?.tipo_conta==='sindico'||me?.user?.perfil==='admin';
 function set(k,v){setForm(x=>({...x,[k]:v}))}function parcel(i,k,v){setForm(x=>({...x,parcelas:x.parcelas.map((p,n)=>n===i?{...p,[k]:v}:p)}))}
 function addParcel(){setForm(x=>({...x,parcelas:[...x.parcelas,{numero:x.parcelas.length+1,valor:'',vencimento:''}]}))}function removeParcel(i){setForm(x=>({...x,parcelas:x.parcelas.filter((_,n)=>n!==i).map((p,n)=>({...p,numero:n+1}))}))}
 async function save(e){e.preventDefault();try{const payload={...form,parcelas:form.forma_pagamento==='parcelado'?form.parcelas:[],vencimento:form.forma_pagamento==='avista'?form.parcelas[0]?.vencimento:null};await api('/api/autorizacoes-pagamento',{method:'POST',body:JSON.stringify(payload)});setFormOpen(false);setForm({forma_pagamento:'avista',notificar_diretor:true,lembrete_dias_antes:3,parcelas:[{numero:1,valor:'',vencimento:''}]});await load()}catch(e){setError(e.message)}}
 async function act(id,acao){try{await api('/api/autorizacoes-pagamento',{method:'PATCH',body:JSON.stringify({id,acao})});await load()}catch(e){setError(e.message)}}
 async function createDir(e){e.preventDefault();const fd=new FormData(e.currentTarget);try{await api('/api/diretorias',{method:'POST',body:JSON.stringify({tipo:'diretoria',nome:fd.get('nome'),descricao:fd.get('descricao')})});setDirOpen(false);await load()}catch(e){setError(e.message)}}
 async function createDirector(e){e.preventDefault();const fd=new FormData(e.currentTarget);try{await api('/api/diretorias',{method:'POST',body:JSON.stringify({tipo:'diretor',diretoria_id:fd.get('diretoria_id'),nome:fd.get('nome'),email:fd.get('email'),whatsapp:fd.get('whatsapp'),senha:fd.get('senha')})});setDirectorOpen(false);await load()}catch(e){setError(e.message)}}
 function whatsapp(x){const dir=dirs.find(z=>z.id===x.diretoria_id),phone=dir?.diretores?.find(z=>z.ativo&&z.whatsapp)?.whatsapp?.replace(/\D/g,'');if(!phone){setError('Nenhum WhatsApp ativo cadastrado para esta diretoria.');return}const p=phone.startsWith('55')?phone:'55'+phone;const msg=`Soluções Condo - Nova autorização de pagamento\nFornecedor: ${x.fornecedor_nome}\nNota: ${x.numero_nota}\nValor: ${brl(x.valor_total)}\nDiretoria: ${x.diretoria}\nStatus: ${String(x.status).replaceAll('_',' ')}`;window.open(`https://wa.me/${p}?text=${encodeURIComponent(msg)}`,'_blank')}
 return <div className="pay-auth-page"><header className="pay-head"><div><button className="pay-back" onClick={()=>location.href='/dashboard'}>← Voltar ao painel</button><h1>Autorização de Pagamentos</h1><p>Fluxo de validação entre Administração e Diretoria.</p></div><div className="pay-actions">{isAdmin&&<><button onClick={()=>setDirOpen(true)}>+ Diretoria</button><button onClick={()=>setDirectorOpen(true)}>+ Diretor</button></>}{!isDirector&&<button className="primary" onClick={()=>setFormOpen(true)}>+ Nova autorização</button>}</div></header>
 {error&&<div className="pay-error">{error}<button onClick={()=>setError('')}>×</button></div>}
 <section className="pay-metrics"><div><small>Pendentes</small><strong>{items.filter(x=>x.status==='aguardando_aprovacoes').length}</strong></div><div><small>Autorizadas</small><strong>{items.filter(x=>x.status==='autorizada_pagamento').length}</strong></div><div><small>Valor autorizado</small><strong>{brl(items.filter(x=>x.status==='autorizada_pagamento').reduce((n,x)=>n+Number(x.valor_total),0))}</strong></div><div><small>Diretorias</small><strong>{dirs.length}</strong></div></section>
 <section className="pay-card"><div className="pay-toolbar"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todas as diretorias</option>{dirs.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select><button onClick={()=>window.open('/api/reports/autorizacoes-pagamento','_blank')}>Gerar relatório PDF</button><button onClick={load}>Atualizar</button></div>{loading?<div className="pay-empty">Carregando...</div>:!visible.length?<div className="pay-empty">Nenhuma autorização encontrada.</div>:<div className="pay-list">{visible.map(x=><article className="pay-item" key={x.id}><div className="pay-item-head"><div><span className="pay-dir">{x.diretoria}</span><h3>{x.fornecedor_nome}</h3><p>NF {x.numero_nota} • {x.forma_pagamento==='parcelado'?'Parcelado':'À vista'} • criado por {x.criado_por_nome}</p></div><span className={'pay-status '+x.status}>{String(x.status).replaceAll('_',' ')}</span></div><div className="pay-grid"><div><small>Valor total</small><strong>{brl(x.valor_total)}</strong></div><div><small>Descrição</small><strong>{x.descricao}</strong></div><div><small>Parcelas / vencimentos</small><strong>{(x.parcelas||[]).map(p=>`${p.numero}ª ${brl(p.valor)} - ${d(p.vencimento)}`).join(' | ')}</strong></div></div><div className="pay-signatures"><div className={x.administrador_aprovou?'signed':'pending'}><b>{x.administrador_aprovou?'✓':'○'} Administração</b><span>{x.administrador_aprovou?`${x.administrador_nome} • ${dt(x.administrador_assinado_em)}`:'Assinatura pendente'}</span></div><div className={x.diretor_aprovou?'signed':'pending'}><b>{x.diretor_aprovou?'✓':'○'} Diretor</b><span>{x.diretor_aprovou?`${x.diretor_nome} • ${dt(x.diretor_assinado_em)}`:'Assinatura pendente'}</span></div></div>{x.status==='aguardando_aprovacoes'&&<div className="pay-row-actions">{isAdmin&&!x.administrador_aprovou&&<button className="approve" onClick={()=>act(x.id,'aprovar_admin')}>Assinar como Administrador</button>}{isDirector&&!x.diretor_aprovou&&<button className="approve" onClick={()=>act(x.id,'aprovar_diretor')}>Assinar como Diretor</button>}<button onClick={()=>whatsapp(x)}>Notificar via WhatsApp</button>{(isAdmin||isDirector)&&<button className="reject" onClick={()=>act(x.id,'rejeitar')}>Rejeitar</button>}</div>}</article>)}</div>}</section>
 {formOpen&&<div className="pay-modal-bg"><form className="pay-modal" onSubmit={save}><h2>Nova autorização</h2><label>Diretoria<select required value={form.diretoria_id||''} onChange={e=>set('diretoria_id',e.target.value)}><option value="">Selecione</option>{dirs.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><div className="pay-form-grid"><label>Fornecedor<input required value={form.fornecedor_nome||''} onChange={e=>set('fornecedor_nome',e.target.value)}/></label><label>Número da nota<input required value={form.numero_nota||''} onChange={e=>set('numero_nota',e.target.value)}/></label><label className="full">Serviço / descrição<textarea required value={form.descricao||''} onChange={e=>set('descricao',e.target.value)}/></label><label>Forma de pagamento<select value={form.forma_pagamento} onChange={e=>set('forma_pagamento',e.target.value)}><option value="avista">À vista</option><option value="parcelado">Parcelado</option></select></label><label>Valor total<input type="number" min="0" step="0.01" required value={form.valor_total||''} onChange={e=>set('valor_total',e.target.value)}/></label></div><h3>{form.forma_pagamento==='parcelado'?'Parcelas':'Vencimento'}</h3>{form.parcelas.map((p,i)=><div className="pay-parcel" key={i}>{form.forma_pagamento==='parcelado'&&<input type="number" step="0.01" placeholder={`Valor ${i+1}ª`} required value={p.valor} onChange={e=>parcel(i,'valor',e.target.value)}/>}<input type="date" required value={p.vencimento} onChange={e=>parcel(i,'vencimento',e.target.value)}/>{form.forma_pagamento==='parcelado'&&form.parcelas.length>1&&<button type="button" onClick={()=>removeParcel(i)}>Remover</button>}</div>)}{form.forma_pagamento==='parcelado'&&<button type="button" onClick={addParcel}>+ Adicionar parcela</button>}<label className="pay-check"><input type="checkbox" checked={!!form.notificar_diretor} onChange={e=>set('notificar_diretor',e.target.checked)}/> Notificar diretor ao inserir</label><label>Lembrar vencimento com antecedência de<input type="number" min="0" value={form.lembrete_dias_antes} onChange={e=>set('lembrete_dias_antes',e.target.value)}/> dias</label><label>Observações<textarea value={form.observacoes||''} onChange={e=>set('observacoes',e.target.value)}/></label><div className="pay-modal-actions"><button type="button" onClick={()=>setFormOpen(false)}>Cancelar</button><button className="primary">Cadastrar solicitação</button></div></form></div>}
 {dirOpen&&<div className="pay-modal-bg"><form className="pay-modal small" onSubmit={createDir}><h2>Nova diretoria</h2><label>Nome<input name="nome" required placeholder="Ex.: Diretoria Financeira"/></label><label>Descrição<textarea name="descricao"/></label><div className="pay-modal-actions"><button type="button" onClick={()=>setDirOpen(false)}>Cancelar</button><button className="primary">Criar</button></div></form></div>}
 {directorOpen&&<div className="pay-modal-bg"><form className="pay-modal small" onSubmit={createDirector}><h2>Novo diretor</h2><label>Diretoria<select name="diretoria_id" required><option value="">Selecione</option>{dirs.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><label>Nome<input name="nome" required/></label><label>E-mail<input name="email" type="email" required/></label><label>WhatsApp<input name="whatsapp" required placeholder="(71) 99999-9999"/></label><label>Senha inicial<input name="senha" type="password" minLength="6" required/></label><div className="pay-modal-actions"><button type="button" onClick={()=>setDirectorOpen(false)}>Cancelar</button><button className="primary">Cadastrar diretor</button></div></form></div>}
 </div>
}
