'use client';
import {useEffect,useMemo,useState} from 'react';
import {Bell,Building2,CalendarDays,Check,Clock3,FileText,MapPin,Plus,Users,Wrench} from 'lucide-react';
import {Box,DataTable,Dialog,Field,useOperation,money,stamp} from './OperationUI';

const cap=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const shortDate=v=>v?new Date(v).toLocaleDateString('pt-BR',{timeZone:'America/Bahia'}):'—';

export function CondominiumsPanel({me,onSelect}){
 const condos=me?.condominios||[];
 return <><section className="reference-metrics"><div><Building2/><strong>{condos.length}</strong><span>Condomínios sob sua gestão</span></div><div><FileText/><strong>Dados separados</strong><span>Ambiente independente por condomínio</span></div><div><Users/><strong>{me?.user?.nome||'Equipe'}</strong><span>Acessos conforme o perfil</span></div></section><section className="condo-grid">{condos.map((c,i)=><article className="condo-card" key={c.condominio_id}><div className={`condo-cover cover-${i%3}`}><Building2/><span>{c.nome}</span></div><div className="condo-card-body"><h2>{c.nome}</h2><p><MapPin size={16}/>{c.endereco||'Endereço não informado'}</p><div className="condo-stats"><span><strong>{c.status==='ativo'?'Ativo':cap(c.status)}</strong> Situação</span><span><strong>{cap(c.perfil)}</strong> Seu perfil</span></div><button className="btn primary block" onClick={()=>onSelect(c.condominio_id)}>Selecionar condomínio</button></div></article>)}</section></>;
}

export function NotificationsPanel({auth,go}){
 const x=useOperation(auth,'notificacoes');
 async function mark(id){await x.send({id});}
 return <Box title="Central de avisos do seu condomínio" actions={<button className="btn primary" disabled={x.busy||!x.items.some(i=>!i.lida)} onClick={()=>mark(null)}><Check size={17}/> Marcar como lidas</button>}>
  {x.error&&<p className="errorbox">{x.error}</p>}<div className="notification-list">{x.items.map(n=><button className={`notification-row ${n.lida?'read':''}`} key={n.chave} onClick={async()=>{if(!n.lida)await mark(n.chave);if(n.modulo)go(n.modulo,n.entidade_id)}}><span className={`notification-icon ${n.tom||'blue'}`}>{n.icone==='wrench'?<Wrench/>:n.icone==='clock'?<Clock3/>:<Bell/>}</span><span className="notification-copy"><strong>{n.titulo}</strong><span>{n.mensagem}</span></span><span className="notification-meta"><time>{stamp(n.criado_em)}</time>{!n.lida&&<i/>}</span></button>)}</div>{!x.busy&&!x.items.length&&<p className="empty">Nenhuma notificação no momento.</p>}
 </Box>;
}

export function AgendaPanel({auth}){
 const x=useOperation(auth,'agenda'),[form,setForm]=useState(null);
 const commitments=x.items.filter(i=>i.origem==='agenda'),deadlines=x.items.filter(i=>i.origem!=='agenda');
 async function submit(e){e.preventDefault();await x.send(form);setForm(null)}
 return <><div className="agenda-grid"><Box title="Novo compromisso" actions={<button className="btn primary" onClick={()=>setForm({tipo:'reuniao',titulo:'',inicio:'',fim:'',local:'',responsavel:'',observacoes:''})}><Plus size={16}/> Adicionar</button>}><p>Registre reuniões, assembleias, inspeções e outros compromissos.</p></Box><Box title="Próximos compromissos"><div className="appointment-list">{commitments.slice(0,6).map((i,n)=><article key={i.id}><i className={`dot dot-${n%4}`}/><div><strong>{i.titulo}</strong><span>{shortDate(i.inicio)} • {new Date(i.inicio).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',timeZone:'America/Bahia'})}{i.local?` • ${i.local}`:''}</span><small>{i.responsavel}</small></div></article>)}</div>{!commitments.length&&<p className="empty">Nenhum compromisso cadastrado.</p>}</Box></div><Box title="Vencimentos e manutenções"><DataTable rows={deadlines} columns={[{key:'titulo',label:'Descrição'},{key:'tipo',label:'Tipo',render:r=>cap(r.tipo)},{key:'inicio',label:'Data',render:r=>shortDate(r.inicio)},{key:'local',label:'Local / equipamento'},{key:'responsavel',label:'Responsável'},{key:'status',label:'Status',render:r=><span className={`badge ${r.status==='atrasado'?'red':'orange'}`}>{cap(r.status)}</span>}]}/></Box>{form&&<Dialog title="Novo compromisso" onClose={()=>setForm(null)}><form onSubmit={submit}><Field label="Tipo"><select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}><option value="reuniao">Reunião</option><option value="assembleia">Assembleia</option><option value="inspecao">Inspeção</option><option value="outro">Outro</option></select></Field><Field label="Título"><input required value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})}/></Field><div className="form-grid"><Field label="Início"><input required type="datetime-local" value={form.inicio} onChange={e=>setForm({...form,inicio:e.target.value})}/></Field><Field label="Fim"><input required type="datetime-local" value={form.fim} onChange={e=>setForm({...form,fim:e.target.value})}/></Field><Field label="Local"><input value={form.local} onChange={e=>setForm({...form,local:e.target.value})}/></Field><Field label="Responsável"><input value={form.responsavel} onChange={e=>setForm({...form,responsavel:e.target.value})}/></Field></div><Field label="Observações"><textarea value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})}/></Field>{x.error&&<p className="errorbox">{x.error}</p>}<button className="btn primary block" disabled={x.busy}>Salvar compromisso</button></form></Dialog>}</>;
}

export function ContractsPanel({rows=[],onNew}){
 const active=rows.filter(r=>r.ativo!==false),month=rows.filter(r=>{const d=new Date(r.fim);const n=new Date();return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()}),soon=rows.filter(r=>{const days=(new Date(r.fim)-Date.now())/86400000;return days>=0&&days<=30}),total=rows.reduce((s,r)=>s+Number(r.valor_mensal||0),0);
 return <><section className="reference-metrics four"><div><FileText/><strong>{active.length}</strong><span>Contratos ativos</span></div><div><CalendarDays/><strong>{month.length}</strong><span>Vencem este mês</span></div><div><Clock3/><strong>{soon.length}</strong><span>Vencem em breve</span></div><div><strong className="metric-money">{money(total)}</strong><span>Valor mensal total</span></div></section><Box title="Lista de contratos" actions={<button className="btn primary" onClick={onNew}><Plus size={16}/> Novo contrato</button>}><DataTable rows={rows} columns={[{key:'titulo',label:'Objeto'},{key:'fornecedor',label:'Fornecedor'},{key:'inicio',label:'Início',render:r=>shortDate(r.inicio)},{key:'fim',label:'Término',render:r=>shortDate(r.fim)},{key:'valor_mensal',label:'Valor',render:r=>money(r.valor_mensal)},{key:'reajuste',label:'Reajuste'},{key:'responsavel',label:'Responsável'},{key:'status',label:'Situação',render:r=><span className={`badge ${new Date(r.fim)<new Date()?'red':'green'}`}>{new Date(r.fim)<new Date()?'Vencido':'Em dia'}</span>}]}/></Box></>;
}
