import crypto from 'node:crypto';
import {pool,query} from './db';
import {requireSession} from './session';
export function fail(message,status=400){throw Object.assign(new Error(message),{status})}
export const text=(v,max=4000)=>String(v??'').trim().slice(0,max);
export function uuid(v){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(String(v)))fail('Identificador inválido.');return v}
export function amount(v){const x=Number(v);if(!Number.isFinite(x)||x<0)fail('Informe um valor válido, maior ou igual a zero.');return x}
export function files(value,imagesOnly=false){if(value==null)return [];if(!Array.isArray(value)||value.length>4)fail('Envie até 4 anexos.');let bytes=0;const out=value.map(f=>{if(!f||typeof f.data!=='string'||!/^data:(image\/(jpeg|png|webp)|application\/pdf);base64,[A-Za-z0-9+/=]+$/.test(f.data)||(imagesOnly&&!f.data.startsWith('data:image/')))fail('Anexo inválido. Use JPG, PNG, WEBP ou PDF.');bytes+=f.data.length;if(f.data.length>750000)fail('Cada arquivo deve ter até 500 KB.');return {nome:text(f.nome,150),data:f.data}});if(bytes>2800000)fail('Anexos excedem o limite total.');return out}
export async function body(request){const raw=await request.text();if(raw.length>3500000)fail('Os arquivos excedem o limite da operação.',413);try{return JSON.parse(raw)}catch{fail('Dados inválidos.')}}
export async function staff(request,admin=false){const u=await requireSession(request);if(admin&&!u.is_superadmin&&!['admin','gerente','supervisor'].includes(u.perfil))fail('Acesso restrito à gestão.',403);if(request.method!=='GET'&&u.perfil==='consulta'&&!u.is_superadmin)fail('Seu perfil permite apenas consultas.',403);return u}
export async function transaction(fn){const c=await pool.connect();try{await c.query('BEGIN');const out=await fn(c);await c.query('COMMIT');return out}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
export async function own(c,table,id,cid,lock=false){const allowed=['ordens_servico','checklist_modelos','inventario','materiais','areas_reservaveis','unidades','moradores','comunicados','reservas','ocorrencias','passagens_plantao','manutencoes_planos','fornecedores'];if(!allowed.includes(table))fail('Recurso inválido.');const r=await c.query(`SELECT * FROM ${table} WHERE id=$1 AND condominio_id=$2 ${lock?'FOR UPDATE':''}`,[uuid(id),cid]);if(!r.rowCount||r.rows[0].ativo===false)fail('Registro não encontrado neste condomínio.',404);return r.rows[0]}
export async function event(c,u,entidade,id,acao,dados={}){await c.query('INSERT INTO operacao_eventos(condominio_id,usuario_id,entidade,entidade_id,acao,dados) VALUES($1,$2,$3,$4,$5,$6)',[u.condominio_id,u.id,entidade,id,acao,JSON.stringify(dados)])}
export const numberCode=p=>`${p}-${crypto.randomBytes(5).toString('hex').toUpperCase()}`;
export async function rateLimit(key,max=8){const r=await query(`INSERT INTO operacao_limites(chave,janela,quantidade) VALUES($1,date_trunc('hour',now()),1) ON CONFLICT(chave,janela) DO UPDATE SET quantidade=operacao_limites.quantidade+1 RETURNING quantidade`,[crypto.createHash('sha256').update(key).digest('hex')]);if(r.rows[0].quantidade>max)fail('Muitas tentativas. Tente novamente mais tarde.',429)}
export function localDate(v){const x=String(v||'');if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2}(\.\d{3})?)?(Z|[+-]\d{2}:\d{2})?$/.test(x))fail('Informe data e horário válidos.');const d=new Date(/[Z]|[+-]\d{2}:\d{2}$/.test(x)?x:x+'-03:00');if(!Number.isFinite(d.getTime()))fail('Data inválida.');return d}
