import { pool,query } from '@/lib/db';
import { hashPassword } from '@/lib/auth';
import { requireSession,apiError } from '@/lib/session';
import { assertTeamCapacity,TEAM_LIMIT_PER_CONDO } from '@/lib/licensing';
export const runtime='nodejs';
const s=v=>String(v??'').trim();
async function owner(request,condominioId){const u=await requireSession(request);if(u.tipo_conta!=='sindico'||u.is_superadmin)throw Object.assign(new Error('Acesso exclusivo ao síndico.'),{status:403});const r=await query(`SELECT id FROM condominios WHERE id=$1 AND sindico_id=$2`,[condominioId,u.id]);if(!r.rowCount)throw Object.assign(new Error('Condomínio não pertence a este síndico.'),{status:403});return u}
export async function GET(request){try{const url=new URL(request.url);const cid=url.searchParams.get('condominio_id');const u=await owner(request,cid);const r=await query(`SELECT us.id,us.nome,us.email,uc.perfil,uc.ativo FROM usuario_condominios uc JOIN usuarios us ON us.id=uc.usuario_id WHERE uc.condominio_id=$1 AND us.tipo_conta='equipe' AND us.sindico_id=$2 ORDER BY us.nome`,[cid,u.id]);return Response.json({items:r.rows,limite:TEAM_LIMIT_PER_CONDO,utilizados:r.rowCount})}catch(e){return apiError(e)}}
export async function POST(request){let client;try{const b=await request.json();const u=await owner(request,b.condominio_id);await assertTeamCapacity(b.condominio_id);if(!s(b.nome)||!s(b.email)||String(b.senha||'').length<6)return Response.json({error:'Nome, e-mail e senha inicial de pelo menos 6 caracteres são obrigatórios.'},{status:400});const perfil=['admin','supervisor','operacional','consulta'].includes(b.perfil)?b.perfil:'operacional';const hash=await hashPassword(String(b.senha));client=await pool.connect();await client.query('BEGIN');const ur=await client.query(`INSERT INTO usuarios(condominio_id,nome,email,senha_hash,perfil,ativo,is_superadmin,tipo_conta,sindico_id,licenca_status) VALUES($1,$2,$3,$4,$5,true,false,'equipe',$6,'ativo') RETURNING id,nome,email,perfil`,[b.condominio_id,s(b.nome),s(b.email).toLowerCase(),hash,perfil,u.id]);await client.query(`INSERT INTO usuario_condominios(usuario_id,condominio_id,perfil,ativo) VALUES($1,$2,$3,true)`,[ur.rows[0].id,b.condominio_id,perfil]);await client.query('COMMIT');client.release();return Response.json({item:ur.rows[0]},{status:201})}catch(e){if(client){try{await client.query('ROLLBACK')}catch{}client.release()}if(e?.code==='23505')return Response.json({error:'E-mail já cadastrado.'},{status:409});return apiError(e)}}
